//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.NGOCollections = new HashSet<NGOCollection>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Collect_Request_ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Expiry_Date { get; set; }
    
        public virtual Collect_Request Collect_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGOCollection> NGOCollections { get; set; }
    }
}
