//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGOCollection
    {
        public Nullable<System.Guid> NGO_ID { get; set; }
        public Nullable<System.Guid> Employee_ID { get; set; }
        public Nullable<System.Guid> Food_ID { get; set; }
        public Nullable<System.Guid> Collect_Request_ID { get; set; }
        public string isCollected { get; set; }
        public System.Guid ID { get; set; }
    
        public virtual Collect_Request Collect_Request { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Food Food { get; set; }
        public virtual NGO NGO { get; set; }
    }
}
